version: '3.9'
services:
  # postgres db
  postgres:
    image: postgres:12.10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bank
    ports:
    - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # backend api
  api:
    build:
      # build the image from the Dockerfile present in the root directory of the project
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgresql://postgres:password@postgres:5432/bank?sslmode=disable # overwrite the DB_HOST env var during runtime
    depends_on:
      postgres: # wait till postgres service is up and running : https://stackoverflow.com/a/62124080
        condition: service_healthy